version: '3.4'

services:
  app:
    image: wal-g-telegram-info
    container_name: wal-g-telegram-info
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.bin/:/root/
      - ./wal-g-pg-ubuntu-20.04-amd64:/bin/wal-g
    env_file:
      - .env
